# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=30)),
                ('house_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('student_name', models.CharField(max_length=30)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('course_teached', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Course')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='house_students',
            field=models.ManyToManyField(to='polls.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_students',
            field=models.ManyToManyField(to='polls.Student'),
        ),
    ]
