# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160823_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='other_students',
            field=models.ManyToManyField(related_name='_student_other_students_+', to='polls.Student'),
        ),
    ]
